### ISSUE TITLE
Comparison array processing with other languages

### ISSUE THREAD

**Issue by csrabak** [Dyalog/MDAPL#1]
In order to do the best sell as possible for APL, we've to be careful to avoid the  ["Straw man Fallacy"](https://en.wikipedia.org/wiki/Straw_man) when mentioning other languages.

Whereas I concur that for _procedural languages_ "at large" the difference between arrays (1.3 Array Processing) has to be done with nested loops, specially if the language is "low level", it is **not** the case for a seasoned Python programmer who could use a more compact form:

```diff = []
for el1,el2 in zip(actual, forecast):
     diff.append(el1 - el2)
```

Also, note that as Python is not a static language w.r.t. its development, it 'sips' from other languages, as they acknowledge in the itertools module that [were] ". . . inspired by constructs from APL, Haskell, and SML."

So an even more similar to APL construct could have been devised! But, of course this is digression for the Dyalog APL material. . .

My suggestion, then would be to change the explicit Python example to a pseudo-code construct changing the target language to "procedural languages". 

Instead, a footnote mentioning APL is a model that modern languages emulate seems to me a better "propaganda" that trying to show an "example" that could be disputed by the experts of other languages.

HTH

**Comment by RojerGS** [comment]
Hey there @csrabak , thank you for opening up this issue.

You make a valid point about targetting procedural languages with a pseudo-code example, instead of naming out Python explicitly.
However, for the sake of argument, notice that the code snippet you provided does not conform to the 2D nature of the data, so we would actually need something like

```py
diff = [
    [a - f for a, f in zip(a_row, f_row)]
    for a_row, f_row in zip(actual, forecast)
]
```

or

```py
diff = []
for a_row, f_row in zip(actual, forecast):
    diff.append([a - f for a, f in zip(a_row, f_row)])
```

or some variant of these things. You could also replace the loops with maps, but will always have to explicitly provide those instructions to Python.
The only way I can think of, right now, to avoid giving those types of instructions is by resorting to importing a module that does array-oriented operations for you, like NumPy:

```py
import numpy as np
diff = (np.array(actual) - np.array(forecast)).tolist()
```

Of course that, at this point, you would probably not convert back to a Python `list` because you would realise NumPy arrays make your life easier in many ways.

**Comment by csrabak** [comment]
Hi @RojerGS, thanks for engaging in the conversation.

I respect your argument, but except if  want to split hairs about the _printout_ of the two small data structures `actual` and `forecast` on the example at the kernel of the discussion were being treated as two _arrays_ (a.k.a. vectors in other languages) as the formalism about the month's results was not being exploited at this particular subsection.

> To make my point clear: the same way APL could do the subtraction without needing to "think" about "rows" or 
"columns", other languages could also have done this, and then we get trapped in discussions about style, necessity, etc.

Again, I tried to steer away of digging even more in "code golfing" (in this case in Python) where with present incarnations of this language we could write (given the two structures were already available in the program) in one single line using comprehensions.

Also, if we accept wisdom from great authors, note that most of people who use a computer nowadays is used to do an operation like the one in the example in spreadsheets where the results occur as an side effect of the cell's copying of formulas.

So my suggestion is that even if you accept the idea of changing to pseucode, please have in mind that in a language of more procedural nature we could postpone the idea of the 2D nature of the table to the moment it is printed out (as in the early days of COBOL) or shown in a screen in modern technology.

Again HTH and my kudos for doing a lift in MDAPL!
